name: Create Neon Branch
on: [pull_request]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create Branch
        uses: neondatabase/create-branch-action@v6
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }} # or your direct ID
          branch_name: pr-${{ github.event.number }}
          api_key: ${{ secrets.NEON_API_KEY }}
